"""Professional brand constants for Contract Leakage Engine reports."""

from reportlab.lib import colors


class BrandColors:
    """Color palette for professional reports."""

    # Primary brand colors
    PRIMARY_BLUE = colors.HexColor('#1a237e')  # Deep blue
    ACCENT_BLUE = colors.HexColor('#1976d2')   # Lighter blue
    DARK_NAVY = colors.HexColor('#0d1b2a')     # Very dark blue

    # Severity colors
    CRITICAL_RED = colors.HexColor('#d32f2f')
    HIGH_ORANGE = colors.HexColor('#f57c00')
    MEDIUM_YELLOW = colors.HexColor('#fbc02d')
    LOW_GREEN = colors.HexColor('#388e3c')

    # Neutral colors
    DARK_GREY = colors.HexColor('#424242')
    MEDIUM_GREY = colors.HexColor('#757575')
    LIGHT_GREY = colors.HexColor('#e0e0e0')
    VERY_LIGHT_GREY = colors.HexColor('#f5f5f5')
    WHITE = colors.HexColor('#ffffff')
    BLACK = colors.HexColor('#000000')

    # Table colors
    TABLE_HEADER = PRIMARY_BLUE
    TABLE_ROW_LIGHT = VERY_LIGHT_GREY
    TABLE_ROW_DARK = WHITE
    TABLE_BORDER = LIGHT_GREY


class Typography:
    """Typography scale for professional reports."""

    # Font families
    PRIMARY_FONT = 'Helvetica'
    PRIMARY_BOLD = 'Helvetica-Bold'
    PRIMARY_ITALIC = 'Helvetica-Oblique'
    PRIMARY_BOLD_ITALIC = 'Helvetica-BoldOblique'

    # Font sizes (in points)
    COVER_TITLE = 36
    COVER_SUBTITLE = 24
    COVER_METADATA = 10

    SECTION_TITLE = 24
    HEADING_1 = 18
    HEADING_2 = 14
    HEADING_3 = 12

    BODY_LARGE = 12
    BODY = 10
    BODY_SMALL = 9
    TABLE_TEXT = 9
    FOOTER = 8
    CAPTION = 7

    # Line spacing
    BODY_LINE_HEIGHT = 14  # 1.4x for 10pt text
    HEADING_LINE_HEIGHT = 1.2


class Layout:
    """Layout constants for page structure."""

    # Page dimensions (letter size in points)
    PAGE_WIDTH = 612     # 8.5 inches
    PAGE_HEIGHT = 792    # 11 inches

    # Margins (in points, 1 inch = 72 points)
    MARGIN_TOP = 54      # 0.75 inches
    MARGIN_BOTTOM = 54   # 0.75 inches
    MARGIN_LEFT = 54     # 0.75 inches
    MARGIN_RIGHT = 54    # 0.75 inches

    # Spacing
    SECTION_SPACING = 24
    PARAGRAPH_SPACING = 12
    LINE_SPACING = 6


class ReportConfig:
    """Report configuration and metadata."""

    REPORT_TITLE = "Commercial Leakage Analysis Report"
    ORGANIZATION_NAME = "AI Contract & Commercial Leakage Engine"
    FOOTER_LINE_1 = "© 2026 Contract Leakage Analysis System"
    FOOTER_LINE_2 = "Advisory-Only Report • Not Legal Advice"
    FOOTER_LINE_3 = "Powered by Azure AI"

    # Report sections
    COVER_PAGE = True
    EXECUTIVE_SUMMARY = True
    DETAILED_FINDINGS = True
    APPENDIX_CLAUSES = False  # Optional

    # Disclaimers
    DISCLAIMER_TEXT = (
        "This report is generated by an AI-powered system and provides advisory insights only. "
        "It is not legal advice and should not be relied upon as such. "
        "Professional legal review is recommended for all contract matters. "
        "The findings and recommendations are based on pattern analysis and may not capture "
        "all contractual risks or nuances. Financial impact estimates are approximations "
        "based on stated assumptions and should be verified independently."
    )
